### ISSUE TITLE
Not able to create pixel buffer with winit 0.29.2

### ISSUE THREAD

**Issue by paulfrische** [parasyte/pixels#379]
Hello there!
I've tried to create a pixel buffer with the following code but it ain't working with winit 0.29:
```rust
use pixels::{SurfaceTexture, Pixels};
use winit::{
    dpi::PhysicalSize,
    event_loop::EventLoop,
    window::WindowBuilder,
};

const WIDTH: u32 = 64;
const HEIGHT: u32 = 64;

fn main() {
    let event_loop = EventLoop::new().unwrap();

    let window = {
        WindowBuilder::new()
            .with_title("test test window")
            .with_inner_size(PhysicalSize::new(1000, 1000))
            .with_inner_size(PhysicalSize::new(1000, 1000))
            .with_resizable(false)
            .build(&event_loop)
            .unwrap()
    };

    let mut pixels =  {
        let window_size = window.inner_size();
        let surface_texture = SurfaceTexture::new(window_size.width, window_size.height, &window);
        Pixels::new(WIDTH, HEIGHT, surface_texture).unwrap()
    };
}
```
Compiler Error:
```
 error[E0277]: the trait bound `Window: pixels::raw_window_handle::HasRawWindowHandle` is not satisfied
   --> src/main.rs:26:90
    |
26  |         let surface_texture = SurfaceTexture::new(window_size.width, window_size.height, &window);
    |                               -------------------                                        ^^^^^^^ the trait `pixels::raw_window_handle::HasRawWind
owHandle` is not implemented for `Window`
    |                               |
    |                               required by a bound introduced by this call
    |
    = help: the following other types implement trait `pixels::raw_window_handle::HasRawWindowHandle`:
              pixels::raw_window_handle::WindowHandle<'_>
              &'a T
```
The same code works with winit 0.28

**Comment by J-Cake** [comment]
I watched Winit tick over to 0.29.2 a few hours ago 😆. Am having this issue too

**Comment by parasyte** [comment]
winit 0.29 updated `raw-window-handle` ([again](https://github.com/parasyte/pixels/issues/292)). But they reference three versions of it: https://github.com/rust-windowing/winit/blob/v0.29.2/Cargo.toml#L61-L63 via feature flags `rwh_06`, `rwh_05`, and `rwh_04`.

While we are still on `raw-window-handle` 0.5, you should be able to use winit 0.29 by changing its feature flags:

```toml
winit = { version = "0.29", default-features = false, features = ["rwh_05", "x11", "wayland", "wayland-dlopen", "wayland-csd-adwaita"] }
```

I have not personally tested this, but it should be a usable workaround for the time being.

**Comment by nxsaken** [comment]
winit <0.28.7 is also broken on macOS Sonoma (see https://github.com/rust-windowing/winit/issues/2876), the examples crash. 

@parasyte am I understanding correctly that we should just update all winit dependencies in `pixels` and its examples to 0.29 with the compatibility feature flags to close this issue?

**Comment by parasyte** [comment]
I'm not _terribly_ concerned about the examples. The main crate is agnostic to whether `winit` is used for platform integration or something else. The only hard dependency is on `raw-window-handle = "0.5"`. Any projects using `pixels` can choose any version of `winit`, given that it is also compatible with our `raw-window-handle` dependency.

But in short, yes, I think that fixing the examples are the only thing we can do for this issue.

**Comment by jamnut** [comment]
This could be a dumb error on my part, I'm not all that good at Rust (yet).   I used the rwh_05 workaround suggested above but still get type errors.  i tried poking around in both libraries and didn't really get anywhere.  Github Copilot was any help either.  Any suggestions or pointers woud be appriciated, at this point I'd rather not backdown the winit version.  I'm also happy to make another run at changing one of the libraries if someone could give me some guidance.

    let event_loop = EventLoop::new().unwrap();

    let window = {
        WindowBuilder::new()
        .build(&event_loop)
        .unwrap()
    };

    let mut pixels = {
        let surface_texture = SurfaceTexture::new(320, 240, &window);
        Pixels::new(m.width, m.height, surface_texture).unwrap()
    };
    
error[E0277]: the trait bound `Window: pixels::raw_window_handle::HasRawWindowHandle` is not satisfied
   --> src/view.rs:33:61
    |
33  |         let surface_texture = SurfaceTexture::new(320, 240, &window);
    |                               -------------------           ^^^^^^^ the trait `pixels::raw_window_handle::HasRawWindowHandle` is not implemented for `Window`
    |                               |
    |                               required by a bound introduced by this call
    |
    = help: the following other types implement trait `pixels::raw_window_handle::HasRawWindowHandle`:
              pixels::raw_window_handle::WindowHandle<'_>
              &'a T
note: required by a bound in `pixels::SurfaceTexture::<'win, W>::new`
   --> /Users/steveweeks/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pixels-0.13.0/src/lib.rs:150:15
    |
150 | impl<'win, W: HasRawWindowHandle + HasRawDisplayHandle> SurfaceTexture<'win, W> {
    |               ^^^^^^^^^^^^^^^^^^ required by this bound in `SurfaceTexture::<'win, W>::new`
...
174 |     pub fn new(width: u32, height: u32, window: &'win W) -> Self {
    |            --- required by a bound in this associated function


If I change the code to use the deprecated interface (and ignore the warnings).  I get the following.
let surface_texture = SurfaceTexture::new(320, 240, &window.raw_window_handle());

error[E0277]: the trait bound `std::result::Result<winit::raw_window_handle::RawWindowHandle, winit::raw_window_handle::HandleError>: pixels::raw_window_handle::HasRawWindowHandle` is not satisfied
   --> src/view.rs:34:61
    |
34  |         let surface_texture = SurfaceTexture::new(320, 240, &window.raw_window_handle());
    |                               -------------------           ^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `pixels::raw_window_handle::HasRawWindowHandle` is not implemented for `std::result::Result<winit::raw_window_handle::RawWindowHandle, winit::raw_window_handle::HandleError>`
    |                               |
    |                               required by a bound introduced by this call
    |
    = help: the following other types implement trait `pixels::raw_window_handle::HasRawWindowHandle`:
              pixels::raw_window_handle::WindowHandle<'_>
              &'a T
note: required by a bound in `pixels::SurfaceTexture::<'win, W>::new`
   --> /Users/steveweeks/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pixels-0.13.0/src/lib.rs:150:15
    |
150 | impl<'win, W: HasRawWindowHandle + HasRawDisplayHandle> SurfaceTexture<'win, W> {
    |               ^^^^^^^^^^^^^^^^^^ required by this bound in `SurfaceTexture::<'win, W>::new`
...
174 |     pub fn new(width: u32, height: u32, window: &'win W) -> Self {
    |            --- required by a bound in this associated function

**Comment by mkrasnitski** [comment]
Chiming in to say that wgpu 0.19 released last week and bumped their version of `raw-window-handle` to 0.6. It should therefore be possible for `pixels` to bump its `wgpu` dependency and enable using `winit 0.29` with default features.

**Comment by parasyte** [comment]
Sounds good. There's an incomplete update to 0.18 in #386. I don't mind skipping a version, just pointing out that anyone who wants to do this work might find this PR a helpful starting point.

**Comment by mkrasnitski** [comment]
Update: I've been trying to upgrade `winit` and `wgpu` and have run into a few problems with CI:
1. `game-loop` currently only supports winit 0.28. There's an open PR: https://github.com/tuzz/game-loop/pull/21
2. `imgui` hasn't seen a release since april, but does support winit 0.29 if you use it as a git dependency.
3. `imgui-wgpu-rs` only supports wgpu 0.17 and winit 0.27.
4. `fltk` doesn't support raw-window-handle 0.6.

**Comment by oddman621** [comment]
This works for me. Try this:
`winit = { version = "0.29", features = ["rwh_05"] }`

**Comment by parasyte** [comment]
#391 should have closed this.
